In [87]:
import pandas as pd

In [88]:
roll = pd.Series([1, 2, 3, 4, 5])
name = pd.Series(['Sia', 'Ravi', 'Geet', 'Ajeenkya', 'Avinash'])
marks = pd.Series([85, 67, 59, 40, 90])

In [89]:
df = pd.DataFrame({
    'id': roll,
    'name': name,
    'marks':marks
})

In [90]:
df

   id      name  marks
0   1       Sia     85
1   2      Ravi     67
2   3      Geet     59
3   4  Ajeenkya     40
4   5   Avinash     90

In [91]:
df.ndim

2

In [92]:
df.shape

(5, 3)

In [93]:
df.size

15

In [94]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [95]:
"""  
url -> https://mitu.co.in/dataset -> will connect to drive folder

download all the datasets starting with student*
put them in the same file folder as ur current working directory

""";

In [96]:
pwd

'C:\\Users\\u\\Downloads\\itr practical'

In [110]:
df = pd.read_csv("student.csv")

In [111]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [112]:
df.shape

(5, 5)

In [113]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [114]:
# student1.csv

In [115]:
df = pd.read_csv('student1.csv')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [116]:
col = ['roll', 'name', 'class', 'marks', 'age']

In [117]:
df = pd.read_csv('student1.csv', names = col)
df

    roll     name  class  marks  age
0   roll     name  class  marks  age
1      1     anil     TE  56.77   22
2      2     amit     TE  59.77   21
3      3   aniket     BE  76.88   19
4      4  ajinkya     TE  69.66   20
5      5     asha     TE  63.28   20
6      6   ayesha     BE  49.55   20
7      7     amar     BE  65.34   19
8      8    amita     BE  68.33   23
9      9     amol     TE  56.75   20
10    10    anmol     BE  78.66   21

In [123]:
# student3.tsv

In [124]:
df = pd.read_csv('student3.tsv', sep = '\t')

In [125]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21