In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.read_csv('student.csv')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [40]:
df.shape

(5, 5)

In [41]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    5 non-null      int64
 1   name    5 non-null      object
 2   class   5 non-null      object
 3   marks   5 non-null      float64
 4   age     5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [43]:
df.dtypes

roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object

In [44]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [45]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [46]:
df.tail()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [47]:
df.tail(3)

   roll     name class  marks  age
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [48]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20]], dtype=object)

In [49]:
df.T

           0      1       2        3      4
roll       1      2       3        4      5
name    anil   amit  aniket  ajinkya   asha
class     TE     TE      BE       TE     TE
marks  56.77  59.77   76.88    69.66  63.28
age       22     21      19       20     20

In [50]:
# sciling

In [51]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [52]:
df.iloc[1:4, 1:4]

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66

In [53]:
df.iloc[1:5 ,[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [54]:
df.iloc[[1,2,3,4], [0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [55]:
df.iloc[4, 1] = 'geet'

In [56]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     geet    TE  63.28   20

In [57]:
# loc

In [58]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     geet    TE  63.28   20

In [59]:
df.loc[2:5, 'name']

2     aniket
3    ajinkya
4       geet
Name: name, dtype: object

In [60]:
df.loc[2:5,['name', 'class']]

      name class
2   aniket    BE
3  ajinkya    TE
4     geet    TE

In [61]:
df.loc[:, 'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       geet
Name: name, dtype: object

In [62]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       geet
Name: name, dtype: object

In [63]:
df[['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     geet    TE

In [64]:
# methods on columns/series

In [65]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     geet    TE  63.28   20

In [66]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       GEET
Name: name, dtype: object

In [67]:
# add or modify columns

In [68]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     geet    TE  63.28   20

In [69]:
gender = ['m','m','m','m','f']

In [70]:
df['gender'] = gender

In [71]:
df

   roll     name class  marks  age gender
0     1     anil    TE  56.77   22      m
1     2     amit    TE  59.77   21      m
2     3   aniket    BE  76.88   19      m
3     4  ajinkya    TE  69.66   20      m
4     5     geet    TE  63.28   20      f

In [72]:
df['roll'] = df['roll'] + 100

In [73]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     geet    TE  63.28   20      f

In [74]:
# add new column cgpa
# values should =>marks/10 + 1.5

In [75]:
df['cgpa'] = df['marks']/10 + 1.5

In [76]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [77]:
df.sort_values(by= 'name')

   roll     name class  marks  age gender   cgpa
3   104  ajinkya    TE  69.66   20      m  8.466
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
0   101     anil    TE  56.77   22      m  7.177
4   105     geet    TE  63.28   20      f  7.828

In [78]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [79]:
# sort by class and then marks simulteneously and check the result

In [80]:
df.sort_values(by=['class', 'marks'])

   roll     name class  marks  age gender   cgpa
2   103   aniket    BE  76.88   19      m  9.188
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
4   105     geet    TE  63.28   20      f  7.828
3   104  ajinkya    TE  69.66   20      m  8.466

In [81]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [82]:
df["marks"].mean()

np.float64(65.272)

In [83]:
df['marks'].max()

76.88

In [84]:
df.describe()

             roll      marks        age      cgpa
count    5.000000   5.000000   5.000000  5.000000
mean   103.000000  65.272000  20.400000  8.027200
std      1.581139   8.070382   1.140175  0.807038
min    101.000000  56.770000  19.000000  7.177000
25%    102.000000  59.770000  20.000000  7.477000
50%    103.000000  63.280000  20.000000  7.828000
75%    104.000000  69.660000  21.000000  8.466000
max    105.000000  76.880000  22.000000  9.188000

In [85]:
#groupby

In [86]:
gr = df.groupby('class')

In [87]:
gr.groups

{'BE': [2], 'TE': [0, 1, 3, 4]}

In [88]:
gr.get_group('BE')

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188

In [89]:
gr.min()

       roll     name  marks  age gender   cgpa
class
BE      103   aniket  76.88   19      m  9.188
TE      101  ajinkya  56.77   20      f  7.177

In [90]:
gr['marks'].mean()

class
BE    76.88
TE    62.37
Name: marks, dtype: float64

In [91]:
# boolean filtering

In [92]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [93]:
df['marks'] > 60

0    False
1    False
2     True
3     True
4     True
Name: marks, dtype: bool

In [94]:
df[df['marks'] > 60]

   roll     name class  marks  age gender   cgpa
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [95]:
# filter the data of those student -> marks > 60 and belong to BE class

In [96]:
f = df[(df['class']=='BE')&(df['marks']>60)]

In [97]:
f

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188

In [98]:
# drop ->drop columns

In [99]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [100]:
df.drop(4)

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466

In [101]:
df.drop([0,3,2])

   roll  name class  marks  age gender   cgpa
1   102  amit    TE  59.77   21      m  7.477
4   105  geet    TE  63.28   20      f  7.828

In [102]:
# drop name column

In [103]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [104]:
df.drop('name', axis = 1)

   roll class  marks  age gender   cgpa
0   101    TE  56.77   22      m  7.177
1   102    TE  59.77   21      m  7.477
2   103    BE  76.88   19      m  9.188
3   104    TE  69.66   20      m  8.466
4   105    TE  63.28   20      f  7.828

In [105]:
# drop name and class

In [106]:
df.drop(['name','class'], axis = 1)

   roll  marks  age gender   cgpa
0   101  56.77   22      m  7.177
1   102  59.77   21      m  7.477
2   103  76.88   19      m  9.188
3   104  69.66   20      m  8.466
4   105  63.28   20      f  7.828

In [107]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [108]:
df.drop(['gender', 'cgpa'], axis = 1, inplace = True)

In [109]:
df
# create a dataframe
# columns -> roll, gender, cgpa
# roll column will have the same values as that of in the df dataframe

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     geet    TE  63.28   20

In [110]:
newdf = pd.DataFrame({
    'roll': df['roll'],
    'gender':gender,
    'cgpa':df['marks']/10 + 1.5
})
newdf

   roll gender   cgpa
0   101      m  7.177
1   102      m  7.477
2   103      m  9.188
3   104      m  8.466
4   105      f  7.828

In [111]:
pd.merge(df, newdf)

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     geet    TE  63.28   20      f  7.828

In [112]:
# cocat

In [113]:
# load student5.csv

In [114]:
newdf = pd.read_csv('student5.csv')
newdf

  roll\tname\tclass\tmarks\tage
0      1\tsurbhi\tTE\t67.44\t23
1       2\tsujay\tTE\t74.12\t22
2     3\tsubhash\tBE\t82.44\t21
3      4\tsachin\tTE\t59.33\t21
4     5\tshalini\tTE\t63.45\t20

In [115]:
pd.concat([df, newdf], ignore_index= True)

    roll     name class  marks   age roll\tname\tclass\tmarks\tage
0  101.0     anil    TE  56.77  22.0                           NaN
1  102.0     amit    TE  59.77  21.0                           NaN
2  103.0   aniket    BE  76.88  19.0                           NaN
3  104.0  ajinkya    TE  69.66  20.0                           NaN
4  105.0     geet    TE  63.28  20.0                           NaN
5    NaN      NaN   NaN    NaN   NaN      1\tsurbhi\tTE\t67.44\t23
6    NaN      NaN   NaN    NaN   NaN       2\tsujay\tTE\t74.12\t22
7    NaN      NaN   NaN    NaN   NaN     3\tsubhash\tBE\t82.44\t21
8    NaN      NaN   NaN    NaN   NaN      4\tsachin\tTE\t59.33\t21
9    NaN      NaN   NaN    NaN   NaN     5\tshalini\tTE\t63.45\t20

In [116]:
f = df[(df['marks'] > 60) & (df['class'] == 'BE')]

In [117]:
f.to_csv('op.csv', index= False)